config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]

    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "search" => "searches#search"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :evaluation,presence:true



  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50}


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end




  

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

def create
  @book = Book.find(params[:book_id])
  @comment = current_user.book_comments.new(book_comment_params)
  @comment.book_id = @book.id
  @comment.save
  render :index
end

def destroy
  @book = Book.find(params[:book_id])
  BookComment.find(params[:id]).destroy
  render :index
end

def book_comment_params
    params.require(:book_comment).permit(:comment)
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @comment = BookComment.new
  end

  def index
    @book  = Book.new
    @books = Book.all.order(params[:aaa])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id, :evaluation, :tag)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

   # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end

  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment_index.html.erb
<table>
  <tbody>
    <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to(book.user) do %>
          <%= image_tag book_comment.user.get_profile_image, size:'100x100' %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <td><% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-sm btn-danger", method: :delete, remote: true %>
          <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/book_comments/_form.html.erb
<%= form_with model:[book, comment], url: book_book_comments_path(book), local: false do |f| %>
  <%= f.text_area :comment, id: "comment_textarea" %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/index.js.erb
$(".comment_index_<%= @book.id %>").html("<%= escape_javascript(render partial: 'book_comments/comment_index', locals: {book: @book}) %>");
$('#comment_textarea').val("");

app/views/books/_evaluation.html.erb
<div id="rate_<%= book.id %>" class="form-group"></div>
<script>
  $('#rate_<%= book.id%>').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half      : false,
    readOnly: true,
    score: <%= book.evaluation %>,
  });
</script>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :tag,'Category' %>
    <%= f.text_field :tag, class: 'form-control book_tag' %>
  </div>
  <% if book.id === nil %>
    <div class="form-group" id="star">
      <%= f.label :evaluation,'Rate' %>
      <%= f.hidden_field :evaluation, id: :review_star, class:'form-control' %>
    </div>
    <script>
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[evaluation]',
      half: true,
    });
    </script>
  <% else %>
    <%= render 'evaluation', book: book %>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= book.tag %></td>
        <td class="favorite-btn_<%= book.id %>"><%= render "favorites/favorite", book: book %></td>
        <td>コメント件数：<%= book.book_comments.count %></td>
        <td><%= render "books/evaluation", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', {user: current_user, book: @book} %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(aaa: 'created_at DESC') %> | <%= link_to "評価の高い順", books_path(aaa: 'evaluation DESC') %>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', { user: @book.user, book: @book } %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>


        <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td class="favorite-btn_<%= @book.id %>"><%= render "favorites/favorite", book: @book %></td>
          <td>コメント件数：<%= @book.book_comments.count %></td><br>
          <td><%= render "books/evaluation", book: @book %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>

      <div class="comment_index_<%= @book.id %>"><%= render "book_comments/comment_index", book: @book %></div>
      <div><%= render "book_comments/form", book: @book, comment: @comment %></div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), class: 'text-danger', method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
  $(".favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
  $(".favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_users.html.erb
<% if users.exists? %>
  <% users.each do |user| %>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <td>ユーザーはいません</td>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
<%= render 'users',users: @users %>

app/views/relationships/followings.html.erb
<h2>Follower Users</h2>
<%= render 'users',users: @users %>

app/views/searches/_serach_form.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<% if @range == "User" %><!--検索対象モデルがUser -->
  <h2>Users search for "<%= params[:word] %>"</h2>
  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Introduction</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= user.introduction %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %><!--検索対象モデルがBook -->
  <h2>Books search for "<%= params[:word] %>"</h2>
  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= image_tag book.user.get_profile_image, size: '50x50' %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if user == current_user %>
          <% elsif current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_followings_path(user.id) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user_followers_path(user.id) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </th>
  </tr>
</table>





<div class='row'>
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% elsif current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), class: "btn btn-primary btn-block", method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), class: "btn btn-success btn-block", method: :post %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', {user: current_user, book: @book} %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', { user: @user, book: @book } %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>